### ISSUE TITLE
why is this repo private?

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/notebooks#1]

**Comment by ghost** [comment]
I think because we (the DAMA) are the only ones who are supposed to compose and edit these notebooks.

**Comment by danielballan** [comment]
Actually it's just a default setting on GitHub that I didn't notice. Will
fix when I actually push something.

**Comment by ghost** [comment]
Just when i thought we were the chosen ones :)

**Comment by ericdill** [comment]
looks like the repo is now public, cool!
